# Generated by Django 3.1.5 on 2021-01-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
